apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.port }}
      nodePort: {{ .Values.gateway.nodePort | default 0 }}
  selector:
    app: gateway

---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.users.service.type }}
  ports:
    - port: {{ .Values.users.service.port }}
      targetPort: {{ .Values.users.service.port }}
  selector:
    app: users

---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.orders.service.type }}
  ports:
    - port: {{ .Values.orders.service.port }}
      targetPort: {{ .Values.orders.service.port }}
  selector:
    app: orders